kind: ConfigMap
metadata:
  name: init-producer
  namespace: producer-consumer 
apiVersion: v1
data:
  start-producer.sh: |-
    #!/bin/bash
    set -e
    set -x

    echo "[start-producer.sh] Starting Producer..."

    source /usr/local/python/env/bin/activate && cd /usr/local/python && python3.7 -u /etc/git-repo/producer.py 2>&1
