---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: producer 
  namespace: producer-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer 
  template:
    metadata:
      labels:
        app: producer 
    spec:
      initContainers:
        - name: git-repo
          image: alpine/git
          args:
            - clone
            - --
            - https://github.com/iamniche-too/fs-python
            - /etc/git-repo
          securityContext:
            runAsUser: 0 
          volumeMounts:
            - name: git-repo-rw
              mountPath: /etc/git-repo
      containers:
        - name: consumer 
          image: nichemley/fs-producer-consumer-image
          args: ['/bin/bash', '/etc/config/start-producer.sh']
          volumeMounts:
            - name: git-repo-rw
              mountPath: /etc/git-repo
            - name: git-repo-ro
              mountPath: /etc/config
      volumes:
        - name: git-repo-rw
          emptyDir: {}
        - name: git-repo-ro
          configMap:
            name: init-producer
status: {}
