kind: ConfigMap
metadata:
  name: init-producer
  namespace: producer-consumer 
apiVersion: v1
data:
  start-producer.sh: |-
    #!/bin/bash
    set -e
    set -x

    echo "Starting Producer..."
    export MESSAGE_SIZE_KB="75"

    source /usr/local/python/env/bin/activate && cd /usr/local/python && python3 /etc/git-repo/producer.py
