apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQU9YcW9GWHpuSFZQOGx6UHA3VmIvall3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa09EZ3lORFkwTVRrdFlqY3lOQzAwTVdaakxXRmlPREV0WkRZd01HRmpZalJrTlRSaQpNQjRYRFRJd01ETXdPREV5TkRNek1Wb1hEVEkxTURNd056RXpORE16TVZvd0x6RXRNQ3NHQTFVRUF4TWtPRGd5Ck5EWTBNVGt0WWpjeU5DMDBNV1pqTFdGaU9ERXRaRFl3TUdGallqUmtOVFJpTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBd0o3b2h1UXI4Vk82akpnOVlqak9FaVlGN1pqNWwwcHlEQ0ZpRXlYRQpVRmZoSUVNbjlHNTdTeW9RZkt6R2treERIZld2a1NIV0FSdDhZTytVank1TkNpY0ZtTUZaVy9pM1hMdER2VFdwCnJZYTJPelFHTENIT0ZzNjZob0tIcXgvL3lzYjQ2V0dNb0RGL0JPVUZvWDNrY2crK05EYnd1dXZEaFNOZm5vcWYKSlBpK01FTkE2T3VVcTNmNnZ2bFRUY01VS0NUZnM2Zm1YckpNVFJwTlVsQlpreVVVeWh1Um9tZTBsdFlMeFFJTQp3T0tzcUUrNTR2ZEU5ZDZZVmdEVUJPN3REaEh5SDM0QWpGdHFkYXRCQUpxY0xHYVJhUEJIcVJHc1pIUVlCTDNuCnJBSWEwcm5sY0M4Q3dXM1puRmJoU1hIWHAxaGJiVGlJcmFNWWVWOXNoSWtQV3dJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpEYlZmd1ppYUJWbVNzeEpONDNRNWZldU5iQlRxYXViVnpHOGNzbFNoZ0xEVlB5eVNoQU9XS3BUVlE4cjA3U0cxCjV6cDEyYmVsR3V5Mm12SzVGUkJOVlRsaXowZ0h0b2xicXpaTFczc0ovb1dnaVJKRjlVYkFMRW82ZDRLMEI1SDMKdmp2Zy8yWHhYeThMRUJ5UVVSeTBseE8zVmFtZHNyNlNjOFdVWkJyeGNzMjl4RVFnUkt1Y25nTUVUcFVrNXZCUApzWG42NVpubUdFVE9uQ3JaYlhvcjlxNU01cVdBblB6QjE4dC9iWTg4WmQzTkthQXBFN1VkNlNMbFFTaXFtbXBLCmZ3UVpxcVVQZGh2b2ZCb2lqV2RzR3AvSzVRTGVxNjB5RGVQaXhuOUZaSnRQREVwUkc5NGYzdXRCbTliM2RwMWcKN2xGaXN4blhnZWhFQ1VEVDNrRWwzdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.234.145.8
  name: cluster-1
contexts:
- context:
    cluster: cluster-1
    user: user-1
  name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
- name: user-1
  user:
    auth-provider:
      config:
        access-token: ya29.c.KpABwQeZToHJFHrhlwjc7sqF9_KvowIzJ8Qo7dyeBlupGu4GV69Rb3fDKrBDrcHpJexhgeY0ZLps2uN35sUH8dzp7HsXAQ0KIe07hcYqbClV7kEBoQL3210pVeJjbUyhOdsHrZdQnIpf23yH6PIbtNFSnnyXC9dwGhTMaCrQqLKeFinnq43WiWJiVbr4AisN5zeW
        expiry: "2020-03-08T16:57:44.931896399Z"
      name: gcp
