kind: ConfigMap
metadata:
  name: init-consumer 
  namespace: producer-consumer 
apiVersion: v1
data:
  start-consumer.sh: |-
    #!/bin/bash
    set -e
    set -x

    echo "[start-consumer.sh] - Starting Consumer (v2) ..."

    # needs python3.7 for asyncio
    source /usr/local/python/env/bin/activate && cd /usr/local/python && python3.7 -u /etc/git-repo/fs_consumer2.py 2>&1
