kind: ConfigMap
metadata:
  name: init-consumer 
  namespace: producer-consumer 
apiVersion: v1
data:
  start-consumer.sh: |-
    #!/bin/bash
    set -e
    set -x

    # Note - needs to be exported to ensure it is picked up by python process
    # export ENDPOINT_URL=http://localhost:8080
    export ENDPOINT_URL=print

    echo "Starting Consumer with endpoint $ENDPOINT_URL"

    source /usr/local/python/env/bin/activate && cd /usr/local/python && python3 /etc/git-repo/consumer.py
