---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: consumer
  namespace: producer-consumer
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      initContainers:
        - name: git-clone
          image: alpine/git
          args:
            - clone
            - --
            - https://github.com/iamniche-too/fs-python
            - /usr/local/fs-python
          securityContext:
            runAsUser: 1
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: git-repo-rw
              mountPath: /usr/local/fs-python
        - name: python-init
          image: ubuntu 
          command: ['/bin/bash', '/etc/python-init/init.sh']
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: git-repo-rw
              mountPath: /usr/local/fs-python
            - name: python-init-ro
              mountPath: /etc/python-init
      containers:
        - name: busybox
          image: busybox
          args: ['tail', '-f', '/dev/null']
          volumeMounts:
            - name: git-repo-rw
              mountPath: /usr/local/fs-python
            - name: python-init-ro
              mountPath: /etc/python-init
      volumes:
        - name: git-repo-rw
          emptyDir: {}
        - name: python-init-ro
          configMap:
            name: python-init 
status: {}
