---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: consumer
  namespace: producer-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      initContainers:
        - name: git-repo
          image: alpine/git
          args:
            - clone
            - --
            - https://github.com/iamniche-too/fs-python
            - /etc/git-repo
          securityContext:
            runAsUser: 0 
          volumeMounts:
            - name: git-repo-rw
              mountPath: /etc/git-repo
      containers:
        - name: consumer 
          image: nichemley/fs-producer-consumer-image 
          args: ['/bin/bash', '/etc/config/start-consumer.sh']
          volumeMounts:
            - name: git-repo-rw
              mountPath: /etc/git-repo
            - name: git-repo-ro
              mountPath: /etc/config
      volumes:
        - name: git-repo-rw
          emptyDir: {}
        - name: git-repo-ro
          configMap:
            name: init-consumer 
status: {}
