kind: ConfigMap
metadata:
  name: init-consumer 
  namespace: producer-consumer 
apiVersion: v1
data:
  start-consumer.sh: |-
    #!/bin/bash
    set -e
    set -x

    echo "[start-consumer.sh] - Starting Consumer..."

    source /usr/local/python/env/bin/activate && cd /usr/local/python && python3 -u /etc/git-repo/consumer.py
