---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: consumer
  namespace: producer-consumer
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: consumer-node
                  operator: In
                  values: ["true"]
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["consumer"]
              topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: git-repo
          image: alpine/git
          args:
            - clone
            - --
            - https://github.com/jezaustin/fs-python
            - /etc/git-repo
          securityContext:
            runAsUser: 0 
          volumeMounts:
            - name: git-repo-rw
              mountPath: /etc/git-repo
        # sysctl settings (kernel parameters)
        - name: init-sysctl
          image: busybox
          command:
            - sh
            - -c
            - sysctl -w vm.swappiness=1; sysctl -w vm.dirty_ratio=60; sysctl -w vm.dirty_background_ratio=5; sysctl -w net.ipv4.tcp_max_syn_backlog=1024; sysctl -w net.ipv4.tcp_max_tw_buckets=262144; sysctl -w net.ipv4.tcp_rmem='4096 87380 33554432'; sysctl -w net.ipv4.tcp_wmem='4096 65536 33554432'
          securityContext:
            privileged: true
      containers:
        - name: consumer 
          image: nichemley/fs-producer-consumer-image 
          args: ['/bin/bash', '/etc/config/start-consumer.sh']
          volumeMounts:
            - name: git-repo-rw
              mountPath: /etc/git-repo
            - name: git-repo-ro
              mountPath: /etc/config
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
      volumes:
        - name: git-repo-rw
          emptyDir: {}
        - name: git-repo-ro
          configMap:
            name: init-consumer
status: {}
