apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lRTUtZcmFjL3BRMlNIai90VHZnSWU1VEFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRNU9UTmhPREZrT1MxbU5XWXdMVFF5TldRdFlXVmlaUzA1TURWaE1qWmxOMlJqT1RZdwpIaGNOTWpBd01qQTJNVFV6TVRFNVdoY05NalV3TWpBME1UWXpNVEU1V2pBdk1TMHdLd1lEVlFRREV5UTVPVE5oCk9ERmtPUzFtTldZd0xUUXlOV1F0WVdWaVpTMDVNRFZoTWpabE4yUmpPVFl3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNyR0VVWHBnV3VlOC9mdGFwL1lEalNXblV1UFFjeVVnZkhxc1NVcEpjbwpKR0NURE5OaFhjVllraXFKUkViOTgzUDlJQjZzcEtkYkNtbm9RemE0dVFnbXl3QVpyWmZ0UnMwcWNHV0pKdXFQClkrMExOck9tenRwQTVxdTFEMFZ2T3dtK3JsLy9naUVCcElhSUs2RndzSEJtVFVRK1ltR3V3cEU0bmU1YVVQdS8KYXpUS3grbHk3SDI0TlB2ZVFsSUlFR0kyeEtQemtML0JQdW9rTnNjR0wwZ2dpQ01tVkIxODgrUUl4T1U3N1V0TQpJSUdWUjc4R1NoNmFHQ0EvVHZtUWZtQ01qSktibkYwRUtBVEttNDdlR3hJUTh0QzNhRXI5NVNrN1JMaGd5TitjCjlqdFM5SjFza2lETHBLSUx0UWhzNHUvY1hDVjJGNVhzdTFhSkFaUmpuYmNKQWdNQkFBR2pJekFoTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBMgpucVFsYm9uSDg2THRkNkJsakxBWk1qcmF6dTdlMmdGaENKZ2d1Rnh1UjF0N3ZyTUJVNktYVityQ2FMWDVZekRrCm0yYmF2NEk2em9hZ1p4SjZSejVvbVltN09CczZ6czBqcWltOWxZeGhndmtYcHBvSWlvSGdWRWx3eks2WW1ZTncKN09GRmhrY0Vaczl3ZUZnZjlYeWEzSmdEYUlYREZTbWdKUVg2WDErdDdnWTlNV2hxMm9QamM1MDF5emhIVWlUbQpJYmZJamFhVzFlVmtHT1g4eGdmTjc2WnJiNWtuM0dCSncvSm5QMW1qSFgzajd0MXFRSERpNit4MXNjYUx1MTFECjNSbitSVXZHd3N0dGdncWluaTdGWjFZdkdneHZsTisrQzF5aHhsQVBlSEI0SXRvbWJVT2Q0d3hwdm52T2RUeFoKYUxDUVFTTHJPZTQwODdmenYybFIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://35.189.97.204
  name: cluster-1
contexts:
- context:
    cluster: cluster-1
    user: user-1
  name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
- name: user-1
  user:
    auth-provider:
      config:
        access-token: ya29.c.KpABvAfgWkvFv31gSv8nu-TwUslb5zOle2CpXgAc-0qy4xgBKqb1DKELeVMReP3yB9rNHoVTVP_XHwT37yz2_VIKOTrD28OiOFsFW4FoYWFY7UtXZVTbv1-wFewmY8JS1AJ1PUzpufmpJM0aw6uTuchLfjPBVnrbDjJ27AyafN3H1PImEYOXQIN4l3YM4t0z2VCd
        expiry: "2020-02-06T17:52:33.801143831Z"
      name: gcp
