apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQU9qMEcyNXhUTktvNDhDRjhtZFJGbll3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa01ERmxZekE0TmpndE5tUmtPQzAwTjJJMUxXRTBOVFl0WVdaa1ptWTRNMk5tTkRreApNQjRYRFRJd01ESXdOREV6TURJeU5Gb1hEVEkxTURJd01qRTBNREl5TkZvd0x6RXRNQ3NHQTFVRUF4TWtNREZsCll6QTROamd0Tm1Sa09DMDBOMkkxTFdFME5UWXRZV1prWm1ZNE0yTm1ORGt4TUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBa1ZOUHZzMkE5bktlSWJyVkpzcXpkekhrR01RZDM4b20wY2JoTXM2RwpGM1FOdWsrYWJiWXhjcFV2bWdLYVRvdTVydUZLODB0dlhWSmNIK0N4cDhDV1hDc1FFK280aVI1Yi9hWkRFUXFmCnZzcmtYVW5MNVJVTjhxbUNLYXZRT2xUZTNkRTZvdmtocHNZQTkzZ2JoQmc4L0xwMWUvSlFXbVIvMW5JcFFjamoKZ0FaMGpjeU5nNDg0WEJvN3JnTXAzVDltaDNJMmE4S25icW5DMWNjU2t0NHNlV1psNUk5RlVIWVEveVlDeGdMMgo1Q3dKOTdvdmFOTzdiMTl0ZUc3UTJURUp1dFdoSHdSbVZITTdmZnhQODR2NmM3ODErblE2M1FzQTRyL3lXMlk4CnRpSkxaNzRuNkpTQzA4SmhVZ2Foa2ZoaGYrT0JwTnJtRW9LcE1TSC9nT2RKc1FJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpUQ0RQL29QNVcyWEQvRXBHdlZVZmRIS1hFcE5EOWZFSldzVC9pZWp2K0lJSHd1Y2tYdzFQM2ZpelF6cjcwakdJCkVNS2xUY25QUWVEZFlOZWVBK1dJRTZEOGRKSlorZTZGd0NscTcrQUt5cks4K1hVZXFidmNjb3BMa3E2TDVqNGsKeWY2RW1LMHpCRE1kOVd0WVM4ZFRxTkp3MUxJaEJOTGhkbU1jWXRaL01WbXRiOW5MKzdZM2lXQjl5Q3dlV2dqUgpiR2QxakNpaVc3Ri95WC9LTHBFdjlnU2ptOXJEVmpueGxzb2VDcDZ6Z2hCY3NXUE4vTGtYZG9Pc2xnNi9qcjFMCllPNmxFLzhYUDR1ODZIai9XQzBtY2U3elVBNXVKZytmL0ltTGZQYm4reGViS3dYeG53V1p5em1VZHBnY2U4UUUKTTRRYm9lOThOZGRTOTBQR0dOVkJyUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.246.36.154
  name: cluster-1
contexts:
- context:
    cluster: cluster-1
    user: user-1
  name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
- name: user-1
  user:
    auth-provider:
      config:
        access-token: ya29.c.KpABvAccSVBTSWlhJdVtawguDxHUV8UrxE-ux7-IrsEoe109-McRg3qgy2pBF6JAUmRlaGpxC2VMDfZMWq7snb3zy976AJP-egSgEKfmj97x3Pu_k6wXn1z9_sXlvSu4zM37mQ_76fo9IZPW-_P_PSzId5U_IHze89IFejqbL_gFQT13LroAM9qBvUTdjzeAsXPq
        expiry: "2020-02-04T17:59:43.829918248Z"
      name: gcp
