apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQUozaFJYc1Y4QmY4dk5WVFFDZU90YVl3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1kyWTFPREU1TkdNdE1XWmtPUzAwTWpNd0xXRXpNV0l0T0RWaU5UbGlZakJoTnpJNApNQjRYRFRJd01ERXpNREE1TXpjek0xb1hEVEkxTURFeU9ERXdNemN6TTFvd0x6RXRNQ3NHQTFVRUF4TWtZMlkxCk9ERTVOR010TVdaa09TMDBNak13TFdFek1XSXRPRFZpTlRsaVlqQmhOekk0TUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBb0tlSEtlY1JIN1I5L0l5NU9pMnA4dk1kTDhndlBGbzZLeS9ZMGwwUQpKRnBnUVdDVjJWdVVrMDZNVW5sb0dRWkdEUC9SOHB0OUlVRTFkZ3F1RkIwT2hSb3dhZWlVZzFzcXlXVDBJTzl5CjBtblpWdW4xOGFFdFBtSFI5ZytwRFpla3ZjVU5rUUxleCtYdXRBdFBRTEthbkQ2OTNMZVI4dWRwanozaWQ3T2YKZUJSVTB0MFF3NUNOOVlNUHdYMHZTV24rQkNDMnpvQmg3NHFIdDNZdG8zNGZ4MGpzR2NLWjRJTFBTOVB4YXpCNQpOQ0FGRk44bmYzVnNBWDY4aElsZ0ZKMWpiWURWU1BuL2NCU0JDRmg0MlpoeHJwak9kM0h2cjEzYkVjbEdIQnNQCkFLZUlUc1N1VWp6Mndobnh5Ym1zRDVScGEzTnZESkV6Q3VFZ1M4cEtOMXVCMlFJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpoY2VoeE00b0hNZzE3SmQ3Rkw5Y1l2dUpKM3BxeThMZWtaOGJjR2lXSnd3TzhtdU9RWmhTMm9JZEV3N3FHQkdMCmdWa3JWMDJoSkRJZ1BxbGxad0tOMGoxaTgrbXoyRTRvaWg0VlFPb3AwZzRBNXRkeU1EVmVLZE1FWWozSElxN1kKQkxWVk82eHJaWDd3VTJ4eXVqTWlmaTlrSzBsL0VvbTBYampGd0dWSWZINjdqWFpIUDVGNW5ORDZWQm1yU2YxNAo0akZFTGh3S0FjZTV6bXNaM3hKc1JXVTc1Um1LR3RkZlJvT3hnbW43THJ6TERIaGRtTXpOQ3lUajRIdmlpOGxMCkNjRGRMdERQV1FvaXV4Y0FnUFByNlNNODIrYWJxT1NHWVBiM3NYZUQyQi9aSDl2UXBlR3RVTytZYk1Ldm81Y2EKZVpVMUtRbkJNT0ZQbm5FbmxpOHNDdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.189.104.128
  name: cluster-1
contexts:
- context:
    cluster: cluster-1
    user: user-1
  name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
- name: user-1
  user:
    auth-provider:
      config:
        access-token: ya29.c.KpABuwchRqkgKF2bozyqr1WEJTXkEYqZh2VxOFaDmYUGMRIktaLriRnr57UuDC280iFrdZXzi0UUm635ZbPhkE1FRtiSTMdafHYH57hlHynwCY44OuE_uvQLN0fAihZDoPVtZ0MsUaHUBIh1LdYi1TUam93MO-3U52EcuR2svBmI6KmkGLGzvQV-l0-K8PJC_0RH
        expiry: "2020-01-30T12:11:20.014733656Z"
      name: gcp
